### ISSUE TITLE
Fountain VS injuben

### ISSUE THREAD

**Issue by YunYouJun** [injuben/injuben#13]
您好，我从 [fountain-zh](https://github.com/leeyupeng/fountain-zh) 看到了本项目。
我最近正在了解剧本格式相关内容，想要请教一下。

[fountain](https://fountain.io/) 似乎更像是一个已成熟的业界写作标准之一。
而现在的 injuben 则似乎是新的一套语法规范，请问使用其替代 Fountain 的具体原因是？

在此之间，有什么对比优劣吗？

**Comment by leeyupeng** [comment]
云游君你好，感谢对 in剧本 项目的关注！

关于新的语法规范（我在帮助里称之为`极简语法`），有两个主要前提：

1.  只适用于中文版，英文版还是采用 Fountain 的官方语法；
2.  极简语法和 Fountain 语法可以同时使用，类似向下兼容的感觉，例子详见 [app/examples/inJuBen_Fountain.txt](/injuben/injuben/blob/master/app/examples/inJuBen_Fountain.txt)。

基于这两个前提，我说一下当初决定针对中文版设计这个新语法规范的一些缘由和初衷。

### 大小写问题
中文里没有大小写之分，而 Fountain 语法中一个主要的元素“角色”是用独占一行的大写字母来表示的。如果中文使用 Fountain 语法，则只能用 `@角色` + 回车 这种方式来撰写，并不是很方便。我参考了网络上一些常见的中文剧本格式，发现很多对话都是采用 `角色：对话` 这种冒号分割的方式，从而设计了相应的语法。

### 标点符号
Fountain 语法中也涉及到一些标点符号，比如点 `.` ，括号 `()` 等，但是在写中文剧本的时候，就可能需要频繁的切换输入法来输入英文标点符号，因此我也针对一些标点做了相应的映射，比如同时兼容 `.` 和 `。` 等，以此减少书写过程中的输入法切换。

### 其他格式
比如封面部分，我直接采用了首页三行文字来分别表示`剧本标题`，`作者姓名`和`出处`，这样就免去了用以下的格式来写封面：

> Title: 标题
Author: 作者
Source: 出处

其实针对这点，我觉得 Fountain 也可以做相应的支持，如果条件允许，或许可以考虑给 Fountain 的作者提交相应的建议。


总之，大多数的极简语法设计都是考虑如何提高中文输入的感受（包括引入一些针对中文场景的关键字等），减少因格式调整导致中断写作思路的可能，我想这也是 Fountain 设计的关键理念之一。另外，这里有一篇关于 in剧本 更为具体的介绍，感兴趣的话也可以关注一下：[in剧本: 免费、开源的中英文剧本写作软件](https://zhuanlan.zhihu.com/p/68393485)。

希望我的回答能有所帮助。再次感谢！

**Comment by YunYouJun** [comment]
感谢您的热情回复。

我正在尝试编写一个通过将剧本语法转换为视觉小说的程序。
在开发时，我本打算自行设计一套语言规范。不过在一番调研后发现了 Fountain 和 injuben。

Fountain 确实存在一些您所说的关于中文支持的问题。以及我起初设想的语法也是 `角色：对话` 形式，与 injuben 颇有相似。

---

我有一些关于 其他格式 这点的建议。

> 比如封面部分，我直接采用了首页三行文字来分别表示剧本标题，作者姓名和出处，这样就免去了用以下的格式来写封面：

我想前缀还是需要的，不过我们可以将关键词使用中文代替。

比如：

> 标题：标题名
> 作者：作者名
> 出处：出自XXX

因为除了标题、作者意外事件，我们可能还有一些其他的头部信息。比如邮箱、日期等，这时我们需要明确的字段来确保不会产生歧义。同时有了明确的字段，我们则不再需要专门去记它的顺序，这样相对友好一些。

再比如存在一种特殊情况（可能比较特例），比如：「鲁迅传」的作者刚好是一个叫鲁迅传的人，这样也容易产生歧义等。

> 鲁迅传
> 鲁迅传

Fountain 最初的设计基于 Markdown 的扩展，而 Markdown 中还有一种流行的配置方案是 [gray-matter](https://github.com/jonschlinkert/gray-matter)。用 `---` 分割的配置项可以被直接作为 JSON 对象解析出来。

```md
---
title: Hello
slug: home
---

Hello world!

```

我查看了 injuben 目前的代码，解析部分似乎是使用 Python 进行编写，因此还需要一台额外的服务器来部署。

我想这部分还可以尝试使用 JavaScript/TypeScript 编写，并发布独立的 npm 包，可以由第三方复用并直接纯前端部署，而无需额外服务器资源。

> 我有一个类似的项目，[web-resume](https://resume.elpsy.cn/editor)，用户按照对应格式即可生成简历，而所有的实时解析生成等内容都在纯前端实现。

---

因为我起初要做的内容还需要转化为交互的程序，所以剧本本质不是单线的，而是有多种路线结果的，所以我可能需要继续扩展一些语法并实现。故我打算参照 Fountain 和 injuben 进行一些实现和扩展。再次感谢您的回复和工作。

**Comment by leeyupeng** [comment]
云游君你好，非常期待这个剧本转换视觉小说的程序！

关于封面页的前缀关键字是一个很好的提议，后面会考虑增加（目前也有部分中文关键字，如`联系人`、`电话`等）。

in剧本 当初采用 Python 的原因之一是有一个英文版的 Fountain 语法分析的开源项目 [screenplain](https://github.com/vilcans/screenplain) ，可以在其基础上直接进行扩展。另外关于 `JavaScript/TypeScript` ，我可能需要投入一定的时间和精力先学习一下`现代 JS`的开发技术，最近也有在关注 [electronjs](https://www.electronjs.org/) ，后续考虑如果用 JS 重写，应该会在`所见即所得`和`跨平台`两个方面投入比较多的设计，但这也取决于我自身对 JS 的了解程度。

另外你提到的 npm 包也是一个不错的解决方案，我唯一不太确认的就是字体处理和打包的部分。目前 in剧本 中文版是通过 Python 加载思源字体文件来保证在任何客户端预览时都可以看到统一的字体而不必依赖于具体的系统环境，Python 本身也可以加入预编译来提高处理速度。全部字体文件大概会有 80+M，不太清楚 JS 处理起来会不会有什么瓶颈。

不管怎样，很感谢你的建议，也预祝程序早日上线。如果有关于 in剧本 的其他问题和建议，也请随时留言。

**Comment by YunYouJun** [comment]
前端方面字体问题应该可以通过外链 CDN 来解决，如 `https://fonts.google.com/` 中提供的字体链接。或打包进仓库中也可以链接使用。这方面应该不会有什么瓶颈。

此外关于 fountain 的插件实现我还发现了 [betterfountain](https://github.com/piersdeseilligny/betterfountain)。（使用 TypeScript 编写，可作为 VSCode 插件使用。）

感谢您的回复，后续我打算尝试投入时间实现前端 JS/TS 相关的一些扩展，再有相关问题再向您探讨请教，谢谢。

**Comment by ChenSomebody** [comment]
云游君你好！

我曾经尝试过使用betterfountain配合VSCode编写剧本，但实际情况是该插件对于中文的支持并不好。我在中文符号的输入上出现了bug，并且无法输出中文的PDF（尝试过更换字体，但只有少部分字体支持中文输出）。

当然，我是一位中学生，电脑能力相当差劲，部分问题可能显得十分幼稚，还望海涵指教。谢谢。
