### ISSUE TITLE
How this online application supports in a collaborative mode?

### ISSUE THREAD

**Issue by songlet** [injuben/injuben#2]
In the case of more than 1 editors on the script, how does the application works for them?

**Comment by leeyupeng** [comment]
The app itself does not support collaborative editing. You might need to use a third-party platform instead, e.g. github, to save script source files for collaborative editing.

**Comment by songlet** [comment]
Understand,;As my teammate can't use properly with Github; I turn them to code.aliyun.com instead.

**Comment by leeyupeng** [comment]
Thank you.
